{
 "title": "Falco Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_falco_events_total{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_falco_events_total{namespace=~\"$namespace\", cluster=~\"$cluster\"},pod)"
    }
   },
   {
    "name": "source",
    "label": "source",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_falco_events_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"},source)"
    }
   },
   {
    "name": "priority",
    "label": "priority",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_falco_events_total{namespace=~\"$namespace\", source=~\"$source\", cluster=~\"$cluster\"},priority)"
    }
   },
   {
    "name": "status",
    "label": "output status",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_outputs_total{cluster=~\"$cluster\"},status)"
    }
   },
   {
    "name": "output",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_outputs_total{status=~\"$status\",cluster=~\"$cluster\"},destination)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(falcosecurity_falcosidekick_falco_events_total,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Priority**: Debug `1` - Informationel `2` - Notice `3` - Warning `4` - Error `5` - Critical `6` - Alert `7` - Emergency `8`\n"
   }
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "by Priority over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Source over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Rule over time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(rule) (increase(falcosecurity_falcosidekick_falco_events_total{source=~\"$source\", priority=~\"$priority\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}