{
 "title": "Falco Logs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   { "name": "datasource", "label": "datasource", "query": "loki" },
   {
    "name": "priority",
    "label": "priority",
    "query": {}
   },
   { "name": "line_filter", "label": "line_filter" }
  ]
 },
 "panels": [
  {
   "title": "Priority counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(priority) (rate({priority=~\".+\"} | logfmt | k8s_ns =~ `$namespace` | priority =~ `$priority` [$__auto]))",
     "legendFormat": "{{priority}}"
    },
    {
     "expr": "count by(priority) (\r\n \r\n rate(\r\n    {namespace=~\"$namespace\"}\r\n      | json\r\n      | __error__=\"\"\r\n      | priority =~ \".+\"\r\n      | priority =~ `$priority`\r\n      [$__auto]\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Rules counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(rule) (rate({priority=~\".+\", rule!=\"Falco internal: metrics snapshot\"} | logfmt | k8s_ns =~ `$namespace` | priority =~ `$priority` [$__auto]))",
     "legendFormat": "{{priority}}"
    },
    {
     "expr": "count by(rule) (\r\n  rate(\r\n    {namespace=~\"$namespace\"}\r\n      | json\r\n      | __error__=\"\"\r\n      | priority =~ `$priority`\r\n      | rule != \"Falco internal: metrics snapshot\"\r\n      [$__auto]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Logs by Priority / Rules (Rango)",
   "type": "timeseries",
   "description": "Número total de Logs por Prioridad y Regla en el rango de tiempo seleccionado",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (priority, rule) (\n  count_over_time (\n    {namespace=~\"$namespace\", app=\"falco\"}\n    | json | __error__ = \"\" \n    | priority != \"\" and rule != \"\" \n    | priority =~ `$priority` \n  [$__range] )\n)"
    }
   ]
  },
  {
   "title": "Realtime logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{priority=~\".+\"} |= `$line_filter` | logfmt | k8s_ns =~ `$namespace` | priority =~ `$priority`"
    },
    {
     "expr": "{namespace=~\"$namespace\"} |= `$line_filter` | json | __error__=\"\" | priority =~ `$priority`"
    }
   ]
  },
  {
   "title": "Priorities Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(priority) (rate({priority=~\".+\"} | logfmt | k8s_ns =~ `$namespace` | priority =~ `$priority` [1m]))",
     "legendFormat": "{{priority}}"
    },
    {
     "expr": "count by(priority) (\r\n  rate(\r\n    {namespace=~\"$namespace\"}\r\n      | json\r\n      | __error__=\"\"\r\n      | priority =~ \".+\"\r\n      | priority =~ `$priority`\r\n      [1m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Rules Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(rule) (rate({priority=~\".+\"} | logfmt | k8s_ns =~ `$namespace` | priority =~ `$priority` [1m]))",
     "legendFormat": "{{priority}}"
    },
    {
     "expr": "count by(rule) (\r\n  rate(\r\n    {namespace=~\"$namespace\"}\r\n      | json\r\n      | __error__=\"\"\r\n      | priority =~ `$priority`\r\n      [1m]\r\n  )\r\n)"
    }
   ]
  }
 ]
}