# This is a basic workflow to help you get started with Actions

name: Notify Downstream DevOps Repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger-downstream:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_FOR_DISPATCH }} # A PAT with repo scope for PTI-WellTrackDevops, or public_repo if PTI-WellTrackDevops is public
          repository: ${{ github.repository_owner }}/PTI-WellTrackDevops # Assuming PTI-WellTrackDevops is under the same owner
          event-type: dashboards-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
